# render.yaml
services:
  - type: web
    name: my-flask-app
    runtime: python-3.11
    env: production
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install --upgrade setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0 app:app
